# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CfM47hOeNhDtdjNFw4msUXRTKGF_8jHN
"""

import pandas as pd

df1= pd.read_excel("Alto Rio Doce.xlsx")
df2= pd.read_excel("Melo.xlsx")

df=pd.concat([df1,df2])

df.head()

df.tail(30)

