# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nzjiOwC3T2wF3sL0mkETaqkdPI0dKonI
"""

import pandas as pd



df = pd.read_csv("/content/sample_data/california_housing_train.csv")

df.head()

df.head(10)

df.rename(columns={"housing_median_age":"idade_media_resedentes"})

df.shape

df.columns

df.dtypes

df.tail()

df.describe()

df["housing_median_age"].unique()

df.groupby("longitude")["total_rooms"].nunique()

